/*
  MapleScouter's crowdsourced Boss Clear (Cut) data: community-measured minimum damage
  thresholds (bossCut/partyBossCut/easyRate) joined with boss requirement physics
  (level/guard/arcaneForce/authenticForce/partyLimit).
  Auto-generated by scripts/scrape-bosscut.mjs. Do not edit by hand.
  Re-run after every MapleScouter update -- see the script header for how this scrapes
  without relying on any hardcoded module ID or chunk filename.
*/

export interface BossCutEntry {
  boss: string;
  name: string;
  difficulty: string;
  level: number;
  guard: number;
  arcaneForce: number | null;
  authenticForce: number | null;
  partyLimit: number;
  bossCut: number | null;
  partyBossCut: number | null;
  easyRate: number | null;
  challenger: number | null;
  renewalDate: string;
  renewalDetail: string;
}

export const BOSSCUT_SCRAPED_AT = "2026-08-04";

export const BOSSCUT_DATA: BossCutEntry[] = [
  { boss: "유피테르", name: "jupiter", difficulty: "Hard", level: 295, guard: 380, arcaneForce: null, authenticForce: 810, partyLimit: 3, bossCut: null, partyBossCut: 125600, easyRate: 0.93024, challenger: null, renewalDate: "", renewalDetail: "" },
  { boss: "카링", name: "kaling", difficulty: "Extreme", level: 285, guard: 380, arcaneForce: null, authenticForce: 480, partyLimit: 6, bossCut: null, partyBossCut: 108350, easyRate: 0.93024, challenger: null, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "대적자", name: "adversary", difficulty: "Extreme", level: 290, guard: 380, arcaneForce: null, authenticForce: 460, partyLimit: 3, bossCut: null, partyBossCut: 113000, easyRate: 0.93024, challenger: null, renewalDate: "2026-05-28", renewalDetail: "재조정" },
  { boss: "칼로스", name: "kalos", difficulty: "Extreme", level: 285, guard: 380, arcaneForce: null, authenticForce: 440, partyLimit: 6, bossCut: null, partyBossCut: 82750, easyRate: 0.93024, challenger: null, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "발드릭스", name: "bardrix", difficulty: "Destiny", level: 290, guard: 380, arcaneForce: null, authenticForce: 700, partyLimit: 1, bossCut: 132800, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "발드릭스", name: "bardrix", difficulty: "Hard", level: 290, guard: 380, arcaneForce: null, authenticForce: 700, partyLimit: 3, bossCut: 132800, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "흉성", name: "maleficStar", difficulty: "Hard", level: 280, guard: 380, arcaneForce: null, authenticForce: 550, partyLimit: 3, bossCut: 120500, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "림보", name: "limbo", difficulty: "Destiny", level: 285, guard: 380, arcaneForce: null, authenticForce: 500, partyLimit: 1, bossCut: 121400, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "", renewalDetail: "" },
  { boss: "림보", name: "limbo", difficulty: "Hard", level: 285, guard: 380, arcaneForce: null, authenticForce: 500, partyLimit: 3, bossCut: 121400, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "", renewalDetail: "" },
  { boss: "유피테르", name: "jupiter", difficulty: "Normal", level: 295, guard: 380, arcaneForce: null, authenticForce: 810, partyLimit: 3, bossCut: 112800, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "대적자", name: "adversary", difficulty: "Destiny", level: 285, guard: 380, arcaneForce: null, authenticForce: 340, partyLimit: 1, bossCut: 110200, partyBossCut: null, easyRate: 0.744192, challenger: null, renewalDate: "", renewalDetail: "" },
  { boss: "세렌", name: "seren", difficulty: "Extreme", level: 280, guard: 380, arcaneForce: null, authenticForce: 200, partyLimit: 6, bossCut: 112000, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "2026-05-28", renewalDetail: "재조정" },
  { boss: "대적자", name: "adversary", difficulty: "Hard", level: 285, guard: 380, arcaneForce: null, authenticForce: 340, partyLimit: 3, bossCut: 110200, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "", renewalDetail: "" },
  { boss: "카링", name: "kaling", difficulty: "Hard", level: 285, guard: 380, arcaneForce: null, authenticForce: 350, partyLimit: 6, bossCut: 109300, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "", renewalDetail: "" },
  { boss: "발드릭스", name: "bardrix", difficulty: "Normal", level: 290, guard: 380, arcaneForce: null, authenticForce: 700, partyLimit: 3, bossCut: 108400, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "검은 마법사", name: "blackMage", difficulty: "Extreme", level: 280, guard: 300, arcaneForce: 1320, authenticForce: null, partyLimit: 6, bossCut: 101300, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "카링", name: "kaling", difficulty: "Destiny", level: 285, guard: 380, arcaneForce: null, authenticForce: 350, partyLimit: 1, bossCut: 109300, partyBossCut: null, easyRate: 1.116288, challenger: null, renewalDate: "", renewalDetail: "" },
  { boss: "림보", name: "limbo", difficulty: "Normal", level: 285, guard: 380, arcaneForce: null, authenticForce: 500, partyLimit: 3, bossCut: 99300, partyBossCut: null, easyRate: 0.885942857142857, challenger: null, renewalDate: "", renewalDetail: "" },
  { boss: "칼로스", name: "kalos", difficulty: "Destiny", level: 285, guard: 380, arcaneForce: null, authenticForce: 330, partyLimit: 1, bossCut: 95100, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "칼로스", name: "kalos", difficulty: "Chaos", level: 285, guard: 380, arcaneForce: null, authenticForce: 330, partyLimit: 6, bossCut: 95100, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "세렌", name: "seren", difficulty: "Destiny", level: 275, guard: 380, arcaneForce: null, authenticForce: 200, partyLimit: 1, bossCut: 40600, partyBossCut: null, easyRate: 0.186048, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "카링", name: "kaling", difficulty: "Normal", level: 285, guard: 380, arcaneForce: null, authenticForce: 330, partyLimit: 6, bossCut: 73300, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "흉성", name: "maleficStar", difficulty: "Normal", level: 280, guard: 380, arcaneForce: null, authenticForce: 400, partyLimit: 3, bossCut: 72300, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "스우", name: "lotus", difficulty: "Extreme", level: 285, guard: 380, arcaneForce: null, authenticForce: null, partyLimit: 2, bossCut: 66800, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "2026-06-06", renewalDetail: "6% 하향" },
  { boss: "칼로스", name: "kalos", difficulty: "Champion", level: 280, guard: 380, arcaneForce: null, authenticForce: 300, partyLimit: 1, bossCut: 49800, partyBossCut: null, easyRate: 0.6415448275862069, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "대적자", name: "adversary", difficulty: "Normal", level: 280, guard: 380, arcaneForce: null, authenticForce: 320, partyLimit: 3, bossCut: 55550, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "", renewalDetail: "" },
  { boss: "칼로스", name: "kalos", difficulty: "Normal", level: 280, guard: 380, arcaneForce: null, authenticForce: 300, partyLimit: 6, bossCut: 49800, partyBossCut: null, easyRate: 0.93024, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "세렌", name: "seren", difficulty: "Champion", level: 275, guard: 380, arcaneForce: null, authenticForce: 200, partyLimit: 1, bossCut: 44300, partyBossCut: null, easyRate: 0.93024, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "카링", name: "kaling", difficulty: "Easy", level: 275, guard: 380, arcaneForce: null, authenticForce: 230, partyLimit: 6, bossCut: 42000, partyBossCut: null, easyRate: 0.93024, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "세렌", name: "seren", difficulty: "Hard", level: 275, guard: 380, arcaneForce: null, authenticForce: 200, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 0.93024, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "대적자", name: "adversary", difficulty: "Easy", level: 270, guard: 380, arcaneForce: null, authenticForce: 220, partyLimit: 3, bossCut: 35250, partyBossCut: null, easyRate: 0.93024, challenger: null, renewalDate: "", renewalDetail: "" },
  { boss: "칼로스", name: "kalos", difficulty: "Easy", level: 270, guard: 380, arcaneForce: null, authenticForce: 200, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 1.8285714285714285, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "검은 마법사", name: "blackMage", difficulty: "Hard", level: 275, guard: 300, arcaneForce: 1320, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 1.023264, challenger: 0.95, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "검은 마법사", name: "blackMage", difficulty: "Champion", level: 275, guard: 300, arcaneForce: 1320, authenticForce: null, partyLimit: 1, bossCut: 40600, partyBossCut: null, easyRate: 1.27908, challenger: 0.95, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "세렌", name: "seren", difficulty: "Normal", level: 270, guard: 380, arcaneForce: null, authenticForce: 200, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 2.2697856, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "진 힐라", name: "verusHilla", difficulty: "Champion", level: 250, guard: 300, arcaneForce: 900, authenticForce: null, partyLimit: 1, bossCut: 40600, partyBossCut: null, easyRate: 2.9190289655172412, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "진 힐라", name: "verusHilla", difficulty: "Hard", level: 250, guard: 300, arcaneForce: 900, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 4.2325919999999995, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "카이", name: "kai", difficulty: "Hard", level: 280, guard: 380, arcaneForce: null, authenticForce: null, partyLimit: 1, bossCut: 40600, partyBossCut: null, easyRate: 1.0482894782608696, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "카이", name: "kai", difficulty: "Normal", level: 270, guard: 380, arcaneForce: null, authenticForce: null, partyLimit: 1, bossCut: 40600, partyBossCut: null, easyRate: 4.0184429999999995, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "듄켈", name: "darknell", difficulty: "Hard", level: 265, guard: 300, arcaneForce: 850, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 4.846550399999999, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "더스크", name: "gloom", difficulty: "Chaos", level: 255, guard: 300, arcaneForce: 730, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 5.0325983999999995, challenger: null, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "가엔슬", name: "slime", difficulty: "Chaos", level: 250, guard: 300, arcaneForce: null, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 4.214391652173913, challenger: null, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "윌", name: "will", difficulty: "Hard", level: 250, guard: 300, arcaneForce: 760, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 5.925628799999999, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "루시드", name: "lucid", difficulty: "Hard", level: 230, guard: 300, arcaneForce: 360, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 2.7907199999999994, challenger: null, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "진 힐라", name: "verusHilla", difficulty: "Normal", level: 250, guard: 300, arcaneForce: 820, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 8.465183999999999, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "스우", name: "lotus", difficulty: "Champion", level: 210, guard: 300, arcaneForce: null, authenticForce: null, partyLimit: 1, bossCut: 40600, partyBossCut: null, easyRate: 10.694552275862069, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "데미안", name: "damien", difficulty: "Hard", level: 210, guard: 300, arcaneForce: null, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 11.628, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "스우", name: "lotus", difficulty: "Hard", level: 210, guard: 300, arcaneForce: null, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 15.5071008, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "듄켈", name: "darknell", difficulty: "Normal", level: 265, guard: 300, arcaneForce: 850, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 30.533267519999995, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "더스크", name: "gloom", difficulty: "Normal", level: 255, guard: 300, arcaneForce: 730, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 25.162991999999996, challenger: null, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "루시드", name: "lucid", difficulty: "Normal", level: 230, guard: 300, arcaneForce: 360, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 31.70211408, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "윌", name: "will", difficulty: "Normal", level: 250, guard: 300, arcaneForce: 760, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 29.628144, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "윌", name: "will", difficulty: "Easy", level: 235, guard: 300, arcaneForce: 560, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 44.442215999999995, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "루시드", name: "lucid", difficulty: "Easy", level: 230, guard: 300, arcaneForce: 360, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 54.66392567999999, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "가엔슬", name: "slime", difficulty: "Normal", level: 220, guard: 300, arcaneForce: null, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 75.85904973913043, challenger: null, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "스우", name: "lotus", difficulty: "Normal", level: 210, guard: 300, arcaneForce: null, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 330.8839979617834, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
  { boss: "데미안", name: "damien", difficulty: "Normal", level: 210, guard: 300, arcaneForce: null, authenticForce: null, partyLimit: 6, bossCut: 40600, partyBossCut: null, easyRate: 348.84, challenger: 0.97, renewalDate: "2026-05-27", renewalDetail: "전 보스 상향조정 최소5%" },
];
