// Always-on Final Damage% per class, generated by scripts/gen-stat-baselines.mjs from
// manifests/v269/skill-formulas.json, pinned by skill id per class and live-verified against real
// characters. Each class has 3 tiers (see comboOrdersData.ts's ComboOrdersTier) — Character Info
// setup always assumes at least tier 1 (Decent Combat Orders active), since every non-legacy
// class's buff guide requires it. Sources combine multiplicatively:
// FinalDamage% = 100 * [(1+a/100)(1+b/100)...] - 100, then *1.10 more if Genesis Liberated, then
// *(1+Reboot bonus/100) more if the character's world is Reboot (see rebootData.ts).
//
// Legacy (pre-revamp) classes are intentionally absent — see masteryData.ts for why.
import { BASE_FINAL_DAMAGE_PERCENT } from "./finalDamageData.generated";
import type { ComboOrdersTier } from "./comboOrdersData";
export { BASE_FINAL_DAMAGE_PERCENT };

const GENESIS_LIBERATION_MULTIPLIER = 1.1;

// strategywiki: Ruin Force Shield (Demon Slayer/Demon Avenger exclusive secondary weapon) grants a
// flat, always-on Final Damage +10% while equipped — folds in as another multiplicative source,
// same as the tiered Combat Orders baseline (see the file-level comment).
const RUIN_FORCE_SHIELD_MULTIPLIER = 1.1;

/** Applies the +10% Genesis Liberation multiplier, the Ruin Force Shield +10% (Demon Slayer/Demon
 *  Avenger only, see classSkillData.ts's ruinForceShield setup option), and, if on a Reboot world,
 *  the level-bracketed Reboot Final Damage bonus (0 for Interactive — see rebootData.ts's
 *  isRebootWorld). */
export function resolveFinalDamagePercent(
  classId: string | undefined,
  isLiberated: boolean | undefined,
  tier: ComboOrdersTier,
  rebootBonusPercent = 0,
  hasRuinForceShield = false,
): number | undefined {
  if (!classId) return undefined;
  const base = BASE_FINAL_DAMAGE_PERCENT[classId]?.[tier];
  if (base === undefined) return undefined;
  // No rounding — this feeds Damage Range's own ×(1+FD/100) term directly (damageRangeData.ts),
  // and rounding here undershoots that result (see gen-stat-baselines.mjs's comment on the same
  // issue at the source). Round only when displaying this percent to the player.
  let multiplier = 1 + base / 100;
  if (isLiberated) multiplier *= GENESIS_LIBERATION_MULTIPLIER;
  if (hasRuinForceShield) multiplier *= RUIN_FORCE_SHIELD_MULTIPLIER;
  if (rebootBonusPercent) multiplier *= 1 + rebootBonusPercent / 100;
  return (multiplier - 1) * 100;
}
