// Weapon Mastery% per class, generated by scripts/gen-stat-baselines.mjs from
// manifests/v270/skill-formulas.json, pinned by skill id per class. Each class has 3 tiers
// (see comboOrdersData.ts's ComboOrdersTier). Character Info setup assumes at least tier 1, with
// Decent Combat Orders active, since every non-legacy class's buff guide requires it.
//
// Legacy pre-revamp classes are intentionally absent. Their Mastery skills were never re-audited
// against this method, so any value for them would be a guess rather than a derived number like
// the 53 classes below.
import { BASE_MASTERY_PERCENT } from "./masteryData.generated";
import type { ComboOrdersTier } from "./comboOrdersData";
export { BASE_MASTERY_PERCENT };

/** Paladin is the one class whose Mastery% also depends on 1H versus 2H weapon choice: a flat +3%
 *  for 1H, which at the base tier reads 90% for 2H and 93% for 1H. It is equipment-driven rather
 *  than skill-level-driven, so it is added on top of whichever Combat Orders tier applies instead
 *  of being its own tier row. Whether it also scales with tier is untested, so it is treated as a
 *  flat +3 always. */
export function resolveMasteryPercent(
  classId: string | undefined,
  weaponHand: "1h" | "2h" | undefined,
  tier: ComboOrdersTier,
): number | undefined {
  if (!classId) return undefined;
  const base = BASE_MASTERY_PERCENT[classId]?.[tier];
  if (base === undefined) return undefined;
  return classId === "paladin" && weaponHand === "1h" ? base + 3 : base;
}
