// Weapon Mastery% per class, generated by scripts/gen-stat-baselines.mjs from
// manifests/v269/skill-formulas.json, pinned by skill id per class. Each class has 3 tiers
// (see comboOrdersData.ts's ComboOrdersTier) — Character Info setup always assumes at least
// tier 1 (Decent Combat Orders active), since every non-legacy class's buff guide requires it.
//
// Legacy (pre-revamp) classes are intentionally absent — their Mastery skills were never
// re-audited against this same method, so any value for them would be an unverified guess
// rather than a confirmed number like the 53 classes below.
import { BASE_MASTERY_PERCENT } from "./masteryData.generated";
import type { ComboOrdersTier } from "./comboOrdersData";
export { BASE_MASTERY_PERCENT };

/** Paladin is the one class where Mastery% itself also depends on 1H vs 2H weapon choice — a flat
 *  +3% for 1H, confirmed against real 2H/1H characters at the base tier (90%/93%). Equipment-driven,
 *  not skill-level-driven, so it's added on top of whichever Combat-Orders tier applies rather than
 *  being its own tier row — untested whether it also scales with tier, treated as a flat +3 always. */
export function resolveMasteryPercent(
  classId: string | undefined,
  weaponHand: "1h" | "2h" | undefined,
  tier: ComboOrdersTier,
): number | undefined {
  if (!classId) return undefined;
  const base = BASE_MASTERY_PERCENT[classId]?.[tier];
  if (base === undefined) return undefined;
  return classId === "paladin" && weaponHand === "1h" ? base + 3 : base;
}
