"use client";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import type { AppTheme } from "../../../../components/themes";
import type { SetupStepDefinition } from "../steps";
import { getClassDataByNexonJobName } from "../data/classSkillData";
import { readCharacterToolData } from "../../../../features/tools/characterToolStorage";
import { resourceImageUrl } from "../../../../lib/mapleResource";
import SetupStepFrame from "./SetupStepFrame";

// Node = [id, displayName, maxLevel]. id is the manifests/v269/v-matrix.json entry id used
// for the haku.network v-matrix icon. Generated by scripts/gen-vmatrix.mjs.
type VMatrixNode = [string, string, number];
interface VMatrixData {
  job: VMatrixNode[];
  boost: VMatrixNode[];
  common: VMatrixNode[];
}

interface VMatrixSetupStepProps {
  theme: AppTheme;
  step: SetupStepDefinition;
  stepNumber: number;
  totalSteps: number;
  jobName?: string;
  direction?: "forward" | "backward";
  confirmedCharacterName?: string;
  value: string;
  onChange: (value: string) => void;
  onBack: () => void;
  onNext: () => void;
  onFinish: () => void;
}

// Per-session cache of fetched class catalogs, keyed by classId.
const catalogCache: Record<string, VMatrixData> = {};

function clamp(v: number, max: number): number {
  return Math.max(0, Math.min(max, Math.round(v) || 0));
}

function parseLevels(raw: string): Record<string, number> {
  if (!raw) return {};
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (parsed && typeof parsed === "object") return parsed as Record<string, number>;
  } catch { /* ignore */ }
  return {};
}

function SkillIcon({ id, name, size = 28 }: { id: string; name: string; size?: number }) {
  const wrapperRef = useRef<HTMLDivElement>(null);
  const fallbackRef = useRef<HTMLDivElement>(null);
  const src = resourceImageUrl("v-matrix", id, "icon.png");
  return (
    <>
      <div ref={wrapperRef} style={{ flexShrink: 0 }}>
        <Image src={src} alt={name} width={size} height={size} unoptimized
          onError={() => {
            if (wrapperRef.current) wrapperRef.current.style.display = "none";
            if (fallbackRef.current) fallbackRef.current.style.display = "block";
          }}
          style={{ borderRadius: "5px", display: "block" }}
        />
      </div>
      <div ref={fallbackRef} style={{ display: "none", width: size, height: size, borderRadius: "5px", flexShrink: 0, background: "rgba(127,127,127,0.18)" }} />
    </>
  );
}

/** Condensed icon tile: icon + level input, full node name shown via tooltip on hover. */
function VMatrixTile({ id, name, level, max, onUpdate, theme }: {
  id: string;
  name: string;
  level: number;
  max: number;
  onUpdate: (v: number) => void;
  theme: AppTheme;
}) {
  const filled = level > 0;
  return (
    <div title={name} style={{
      width: 60, flexShrink: 0,
      border: `1px solid ${filled ? theme.accent : theme.border}`,
      borderRadius: 8,
      background: filled ? `${theme.accent}15` : theme.bg,
      display: "flex", flexDirection: "column", alignItems: "center", gap: 4,
      padding: "6px 4px", boxSizing: "border-box",
    }}>
      <div style={{ opacity: filled ? 1 : 0.5, filter: filled ? "none" : "grayscale(1)", lineHeight: 0 }}>
        <SkillIcon id={id} name={name} size={28} />
      </div>
      <input
        type="text"
        inputMode="numeric"
        aria-label={`${name} level`}
        value={level === 0 ? "" : String(level)}
        placeholder="0"
        onChange={(e) => onUpdate(Number(e.target.value) || 0)}
        onFocus={(e) => { e.currentTarget.style.outlineColor = theme.accent; }}
        onBlur={(e) => {
          e.currentTarget.style.outlineColor = "transparent";
          onUpdate(clamp(parseInt(e.currentTarget.value, 10) || 0, max));
        }}
        style={{
          width: 44, textAlign: "center",
          border: `1px solid ${theme.border}`, borderRadius: 6,
          background: theme.bg, color: theme.text,
          fontFamily: "inherit", fontWeight: 700, fontSize: "0.78rem",
          padding: "0.2rem", boxSizing: "border-box",
          outline: "2px solid transparent", outlineOffset: "2px",
          transition: "outline-color 0.15s ease",
        }}
      />
    </div>
  );
}

function SectionLabel({ label, theme, onMaxAll, onClear }: { label: string; theme: AppTheme; onMaxAll: () => void; onClear: () => void }) {
  const btnStyle: React.CSSProperties = {
    background: "none", border: "none", padding: 0, font: "inherit",
    fontSize: "0.75rem", fontWeight: 800, letterSpacing: "0.05em", textTransform: "uppercase",
    cursor: "pointer",
  };
  return (
    <div style={{
      display: "flex", justifyContent: "space-between", alignItems: "baseline",
      marginBottom: "0.45rem", paddingBottom: "0.25rem", borderBottom: `1px solid ${theme.border}`,
    }}>
      <p style={{
        margin: 0, fontSize: "0.75rem", fontWeight: 800,
        color: theme.muted, letterSpacing: "0.05em", textTransform: "uppercase",
      }}>
        {label}
      </p>
      <div style={{ display: "flex", gap: "1rem" }}>
        <button type="button" onClick={onClear} style={{ ...btnStyle, color: theme.muted }}>
          Clear
        </button>
        <button type="button" onClick={onMaxAll} style={{ ...btnStyle, color: theme.accent }}>
          Max All
        </button>
      </div>
    </div>
  );
}

function NodeSection({ label, nodes, levels, theme, onSet, onSetMany }: {
  label: string;
  nodes: VMatrixNode[];
  levels: Record<string, number>;
  theme: AppTheme;
  onSet: (name: string, level: number) => void;
  onSetMany: (updates: Record<string, number>) => void;
}) {
  if (nodes.length === 0) return null;
  return (
    <div>
      <SectionLabel label={label} theme={theme}
        onMaxAll={() => onSetMany(Object.fromEntries(nodes.map(([, name, max]) => [name, max])))}
        onClear={() => onSetMany(Object.fromEntries(nodes.map(([, name]) => [name, 0])))} />
      <div style={{ display: "grid", gridTemplateColumns: "repeat(6, 60px)", gap: "0.4rem" }}>
        {nodes.map(([id, name, max]) => (
          <VMatrixTile key={name} id={id} name={name} level={levels[name] ?? 0} max={max} theme={theme}
            onUpdate={(v) => onSet(name, v)} />
        ))}
      </div>
    </div>
  );
}

export default function VMatrixSetupStep({
  theme, step, stepNumber, totalSteps, jobName = "",
  confirmedCharacterName, value, onChange, onBack, onNext, onFinish,
}: VMatrixSetupStepProps) {
  const classId = getClassDataByNexonJobName(jobName)?.id;
  const initialValueRef = useRef(value);
  const [catalog, setCatalog] = useState<VMatrixData | null>(classId ? catalogCache[classId] ?? null : null);
  const [loadFailed, setLoadFailed] = useState(false);

  useEffect(() => {
    if (!classId || catalogCache[classId]) return;
    fetch(`/data/vmatrix/${classId}.json`)
      .then((r) => r.json() as Promise<VMatrixData>)
      .then((data) => { catalogCache[classId] = data; setCatalog(data); })
      .catch(() => setLoadFailed(true));
  }, [classId]);

  // Prefill from saved tool data on first land (only when the step has no draft yet).
  useEffect(() => {
    if (initialValueRef.current || !confirmedCharacterName) return;
    const saved = readCharacterToolData<{ levels?: Record<string, number> }>(confirmedCharacterName, "vMatrix");
    if (saved?.levels && Object.keys(saved.levels).length > 0) onChange(JSON.stringify(saved.levels));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const levels = parseLevels(value);

  function setLevel(name: string, level: number) {
    onChange(JSON.stringify({ ...levels, [name]: level }));
  }

  function setLevels(updates: Record<string, number>) {
    onChange(JSON.stringify({ ...levels, ...updates }));
  }

  if (!classId || loadFailed) {
    return (
      <SetupStepFrame theme={theme} stepLabel={step.label} stepNumber={stepNumber} totalSteps={totalSteps}
        description="V Matrix data is not available for this class yet."
        onBack={onBack} onNext={onNext} onFinish={onFinish}
      >
        <p style={{ margin: 0, fontSize: "0.85rem", color: theme.muted, fontWeight: 700 }}>
          No data available for {jobName || "this class"}.
        </p>
      </SetupStepFrame>
    );
  }

  return (
    <SetupStepFrame theme={theme} stepLabel={step.label} stepNumber={stepNumber} totalSteps={totalSteps}
      description="All fields are optional. Fill in what you know."
      onBack={onBack} onNext={onNext} onFinish={onFinish}
    >
      {catalog ? (
        <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
          <NodeSection label="Job Nodes" nodes={catalog.job} levels={levels} theme={theme} onSet={setLevel} onSetMany={setLevels} />
          <NodeSection label="Boost Nodes" nodes={catalog.boost} levels={levels} theme={theme} onSet={setLevel} onSetMany={setLevels} />
          <NodeSection label="Common Nodes" nodes={catalog.common} levels={levels} theme={theme} onSet={setLevel} onSetMany={setLevels} />
        </div>
      ) : (
        <p style={{ margin: 0, fontSize: "0.85rem", color: theme.muted, fontWeight: 700 }}>Loading…</p>
      )}
    </SetupStepFrame>
  );
}
