"use client";

import { useEffect, useRef, useState } from "react";
import { sanitizeDigitsInput } from "../../../../lib/inputUtils";
import Image from "next/image";
import type { AppTheme } from "../../../../components/themes";
import type { SetupStepDefinition } from "../steps";
import { getClassDataByNexonJobName } from "../data/classSkillData";
import { readCharactersStore, selectCharacterByIgn } from "../../model/charactersStore";
import { resourceImageUrl } from "../../../../lib/mapleResource";
import SetupStepFrame from "./SetupStepFrame";
import { LeveledIconTile } from "./LeveledIconTile";

// Node = [id, displayName, maxLevel]. id is the manifests/v269/v-matrix.json entry id used
// for the haku.network v-matrix icon. Generated by scripts/gen-vmatrix.mjs.
type VMatrixNode = [string, string, number];
interface VMatrixData {
  job: VMatrixNode[];
  boost: VMatrixNode[];
  common: VMatrixNode[];
}

interface VMatrixSetupStepProps {
  theme: AppTheme;
  step: SetupStepDefinition;
  stepNumber: number;
  totalSteps: number;
  jobName?: string;
  direction?: "forward" | "backward";
  confirmedCharacterName?: string;
  value: string;
  onChange: (value: string) => void;
  onBack: () => void;
  onNext: () => void;
  onFinish: () => void;
}

// Per-session cache of fetched class catalogs, keyed by classId.
const catalogCache: Record<string, VMatrixData> = {};

const sectionBtnStyle: React.CSSProperties = {
  background: "none", border: "none", padding: 0, font: "inherit",
  fontSize: "0.75rem", fontWeight: 800,
  cursor: "pointer",
};

// Draft levels are strings (blank until touched), matching Oz Rings' pattern so a
// typed "0" doesn't collapse back into an indistinguishable empty state. Values are
// normalized to strings here regardless of the raw JSON's own type, since a prefill
// from saved tool data (real numbers) can land in the same draft as user-typed values.
function parseLevels(raw: string): Record<string, string> {
  if (!raw) return {};
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (parsed && typeof parsed === "object") {
      return Object.fromEntries(
        Object.entries(parsed as Record<string, unknown>).map(([k, v]) => [k, String(v)]),
      );
    }
  } catch { /* ignore */ }
  return {};
}

// Clamps while preserving the string (see parseLevels above).
function clampLevelInput(raw: string, max: number): string {
  const digits = sanitizeDigitsInput(raw);
  if (digits === "") return "";
  return String(Math.min(max, Number(digits)));
}

function SkillIcon({ id, name, size = 28 }: { id: string; name: string; size?: number }) {
  const wrapperRef = useRef<HTMLDivElement>(null);
  const fallbackRef = useRef<HTMLDivElement>(null);
  const src = resourceImageUrl("v-matrix", id, "icon.png");
  return (
    <>
      <div ref={wrapperRef} style={{ flexShrink: 0 }}>
        <Image src={src} alt={name} width={size} height={size} unoptimized
          onError={() => {
            if (wrapperRef.current) wrapperRef.current.style.display = "none";
            if (fallbackRef.current) fallbackRef.current.style.display = "block";
          }}
          style={{ borderRadius: "5px", display: "block" }}
        />
      </div>
      <div ref={fallbackRef} style={{ display: "none", width: size, height: size, borderRadius: "5px", flexShrink: 0, background: "rgba(127,127,127,0.18)" }} />
    </>
  );
}

function SectionLabel({ label, theme, onMaxAll, onClear }: { label: string; theme: AppTheme; onMaxAll: () => void; onClear: () => void }) {
  return (
    <div style={{
      display: "flex", justifyContent: "space-between", alignItems: "baseline",
      marginBottom: "0.45rem", paddingBottom: "0.25rem", borderBottom: `1px solid ${theme.border}`,
    }}>
      <p style={{
        margin: 0, fontSize: "0.75rem", fontWeight: 800,
        color: theme.muted, letterSpacing: "0.05em", textTransform: "uppercase",
      }}>
        {label}
      </p>
      <div style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
        <button type="button" onClick={onClear} style={{ ...sectionBtnStyle, color: theme.muted }}>
          Clear
        </button>
        <span style={{ width: 1, alignSelf: "stretch", background: theme.border, flexShrink: 0 }} />
        <button type="button" onClick={onMaxAll} style={{ ...sectionBtnStyle, color: theme.accent }}>
          Max All
        </button>
      </div>
    </div>
  );
}

function NodeSection({ label, nodes, levels, theme, onSet, onSetMany }: {
  label: string;
  nodes: VMatrixNode[];
  levels: Record<string, string>;
  theme: AppTheme;
  onSet: (name: string, level: string) => void;
  onSetMany: (updates: Record<string, string>) => void;
}) {
  if (nodes.length === 0) return null;
  return (
    <div>
      <SectionLabel label={label} theme={theme}
        onMaxAll={() => onSetMany(Object.fromEntries(nodes.map(([, name, max]) => [name, String(max)])))}
        onClear={() => onSetMany(Object.fromEntries(nodes.map(([, name]) => [name, ""])))} />
      <div className="vmatrix-grid" style={{ display: "grid", gap: "0.4rem" }}>
        {nodes.map(([id, name, max]) => (
          <LeveledIconTile key={name} icon={<SkillIcon id={id} name={name} size={32} />} name={name}
            level={levels[name] ?? ""} max={max} theme={theme}
            onLevel={(v) => onSet(name, clampLevelInput(v, max))} />
        ))}
      </div>
    </div>
  );
}

export default function VMatrixSetupStep({
  theme, step, stepNumber, totalSteps, jobName = "",
  confirmedCharacterName, value, onChange, onBack, onNext, onFinish,
}: VMatrixSetupStepProps) {
  const classId = getClassDataByNexonJobName(jobName)?.id;
  const initialValueRef = useRef(value);
  const [catalog, setCatalog] = useState<VMatrixData | null>(classId ? catalogCache[classId] ?? null : null);
  const [loadFailed, setLoadFailed] = useState(false);

  useEffect(() => {
    if (!classId || catalogCache[classId]) return;
    fetch(`/data/vmatrix/${classId}.json`)
      .then((r) => r.json() as Promise<VMatrixData>)
      .then((data) => { catalogCache[classId] = data; setCatalog(data); })
      .catch(() => setLoadFailed(true));
  }, [classId]);

  // Prefill from saved tool data on first land (only when the step has no draft yet).
  useEffect(() => {
    if (initialValueRef.current || !confirmedCharacterName) return;
    const saved = selectCharacterByIgn(readCharactersStore(), confirmedCharacterName)?.vMatrix;
    if (saved?.levels && Object.keys(saved.levels).length > 0) {
      const asStrings = Object.fromEntries(Object.entries(saved.levels).map(([k, v]) => [k, String(v)]));
      onChange(JSON.stringify(asStrings));
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const levels = parseLevels(value);

  function setLevel(name: string, level: string) {
    onChange(JSON.stringify({ ...levels, [name]: level }));
  }

  function setLevels(updates: Record<string, string>) {
    onChange(JSON.stringify({ ...levels, ...updates }));
  }

  if (!classId || loadFailed) {
    return (
      <SetupStepFrame theme={theme} stepLabel={step.label} stepNumber={stepNumber} totalSteps={totalSteps}
        description="V Matrix data is not available for this class yet."
        onBack={onBack} onNext={onNext} onFinish={onFinish}
      >
        <p style={{ margin: 0, fontSize: "0.85rem", color: theme.muted, fontWeight: 700 }}>
          No data available for {jobName || "this class"}.
        </p>
      </SetupStepFrame>
    );
  }

  return (
    <SetupStepFrame theme={theme} stepLabel={step.label} stepNumber={stepNumber} totalSteps={totalSteps}
      description="Enter your V Matrix node levels."
      onBack={onBack} onNext={onNext} onFinish={onFinish}
    >
      {catalog ? (
        <div className="vmatrix-root" style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
          <style>{`
            .vmatrix-root { container-type: inline-size; }
            .vmatrix-grid { grid-template-columns: repeat(6, 68px); }
            @container (max-width: 410px) {
              .vmatrix-grid { grid-template-columns: repeat(auto-fill, 68px); }
            }
          `}</style>
          <NodeSection label="Job Nodes" nodes={catalog.job} levels={levels} theme={theme} onSet={setLevel} onSetMany={setLevels} />
          <NodeSection label="Boost Nodes" nodes={catalog.boost} levels={levels} theme={theme} onSet={setLevel} onSetMany={setLevels} />
          <NodeSection label="Common Nodes" nodes={catalog.common} levels={levels} theme={theme} onSet={setLevel} onSetMany={setLevels} />
        </div>
      ) : (
        <p style={{ margin: 0, fontSize: "0.85rem", color: theme.muted, fontWeight: 700 }}>Loading…</p>
      )}
    </SetupStepFrame>
  );
}
