"use client";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import type { AppTheme } from "../../../../components/themes";
import type { SetupStepDefinition } from "../steps";
import { getClassDataByNexonJobName } from "../data/classSkillData";
import { readCharacterToolData } from "../../../../features/tools/characterToolStorage";
import { resourceImageUrl } from "../../../../lib/mapleResource";
import SetupStepFrame from "./SetupStepFrame";

// Node = [skillId | null, displayName]. id is the skill.json id for the haku.network icon,
// null when unresolved (placeholder tile shown). Generated by scripts/gen-vmatrix.mjs.
type VMatrixNode = [string | null, string];
interface VMatrixData {
  job: VMatrixNode[];
  boost: VMatrixNode[];
  common: VMatrixNode[];
}

interface VMatrixSetupStepProps {
  theme: AppTheme;
  step: SetupStepDefinition;
  stepNumber: number;
  totalSteps: number;
  jobName?: string;
  direction?: "forward" | "backward";
  confirmedCharacterName?: string;
  value: string;
  onChange: (value: string) => void;
  onBack: () => void;
  onNext: () => void;
  onFinish: () => void;
}

const JOB_MAX = 30;
const BOOST_MAX = 60;
const COMMON_MAX = 30;

// Per-session cache of fetched class catalogs, keyed by classId.
const catalogCache: Record<string, VMatrixData> = {};

function clamp(v: number, max: number): number {
  return Math.max(0, Math.min(max, Math.round(v) || 0));
}

function parseLevels(raw: string): Record<string, number> {
  if (!raw) return {};
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (parsed && typeof parsed === "object") return parsed as Record<string, number>;
  } catch { /* ignore */ }
  return {};
}

function SkillIcon({ id, name, size = 28 }: { id: string | null; name: string; size?: number }) {
  const wrapperRef = useRef<HTMLDivElement>(null);
  const fallbackRef = useRef<HTMLDivElement>(null);
  const src = id ? resourceImageUrl("skill", id, "icon.png") : null;
  if (!src) {
    return <div style={{ width: size, height: size, borderRadius: "5px", flexShrink: 0, background: "rgba(127,127,127,0.18)" }} />;
  }
  return (
    <>
      <div ref={wrapperRef} style={{ flexShrink: 0 }}>
        <Image src={src} alt={name} width={size} height={size} unoptimized
          onError={() => {
            if (wrapperRef.current) wrapperRef.current.style.display = "none";
            if (fallbackRef.current) fallbackRef.current.style.display = "block";
          }}
          style={{ borderRadius: "5px", display: "block" }}
        />
      </div>
      <div ref={fallbackRef} style={{ display: "none", width: size, height: size, borderRadius: "5px", flexShrink: 0, background: "rgba(127,127,127,0.18)" }} />
    </>
  );
}

function LevelInput({ value, onChange, theme, max, label }: {
  value: number; onChange: (v: number) => void; theme: AppTheme; max: number; label: string;
}) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: "0.3rem", flexShrink: 0 }}>
      <input
        type="text"
        inputMode="numeric"
        aria-label={label}
        value={value === 0 ? "" : String(value)}
        placeholder="0"
        onChange={(e) => onChange(Number(e.target.value) || 0)}
        onFocus={(e) => { e.currentTarget.style.outlineColor = theme.accent; }}
        onBlur={(e) => {
          e.currentTarget.style.outlineColor = "transparent";
          onChange(clamp(parseInt(e.currentTarget.value, 10) || 0, max));
        }}
        style={{
          width: "2.4rem",
          border: `1px solid ${theme.border}`,
          borderRadius: "6px",
          background: theme.bg,
          color: theme.text,
          fontFamily: "inherit",
          fontSize: "0.82rem",
          fontWeight: 700,
          padding: "0.25rem 0.35rem",
          textAlign: "center",
          outline: "2px solid transparent",
          outlineOffset: "2px",
          transition: "outline-color 0.15s ease",
        }}
      />
      <span style={{ fontSize: "0.75rem", color: theme.muted, fontWeight: 700 }}>/ {max}</span>
    </div>
  );
}

function SectionLabel({ label, theme }: { label: string; theme: AppTheme }) {
  return (
    <p style={{
      margin: 0, marginBottom: "0.45rem", fontSize: "0.75rem", fontWeight: 800,
      color: theme.muted, letterSpacing: "0.05em", textTransform: "uppercase",
      paddingBottom: "0.25rem", borderBottom: `1px solid ${theme.border}`,
    }}>
      {label}
    </p>
  );
}

function NodeSection({ label, nodes, max, levels, theme, onSet }: {
  label: string;
  nodes: VMatrixNode[];
  max: number;
  levels: Record<string, number>;
  theme: AppTheme;
  onSet: (name: string, level: number) => void;
}) {
  if (nodes.length === 0) return null;
  return (
    <div>
      <SectionLabel label={label} theme={theme} />
      <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
        {nodes.map(([id, name]) => (
          <div key={name} style={{ display: "flex", alignItems: "center", gap: "0.6rem" }}>
            <SkillIcon id={id} name={name} />
            <p style={{ margin: 0, flex: 1, fontSize: "0.82rem", fontWeight: 700, color: theme.text, minWidth: 0 }}>
              {name}
            </p>
            <LevelInput value={levels[name] ?? 0} onChange={(v) => onSet(name, v)} theme={theme} max={max} label={`${name} level`} />
          </div>
        ))}
      </div>
    </div>
  );
}

export default function VMatrixSetupStep({
  theme, step, stepNumber, totalSteps, jobName = "",
  confirmedCharacterName, value, onChange, onBack, onNext, onFinish,
}: VMatrixSetupStepProps) {
  const classId = getClassDataByNexonJobName(jobName)?.id;
  const initialValueRef = useRef(value);
  const [catalog, setCatalog] = useState<VMatrixData | null>(classId ? catalogCache[classId] ?? null : null);
  const [loadFailed, setLoadFailed] = useState(false);

  useEffect(() => {
    if (!classId || catalogCache[classId]) return;
    fetch(`/data/vmatrix/${classId}.json`)
      .then((r) => r.json() as Promise<VMatrixData>)
      .then((data) => { catalogCache[classId] = data; setCatalog(data); })
      .catch(() => setLoadFailed(true));
  }, [classId]);

  // Prefill from saved tool data on first land (only when the step has no draft yet).
  useEffect(() => {
    if (initialValueRef.current || !confirmedCharacterName) return;
    const saved = readCharacterToolData<{ levels?: Record<string, number> }>(confirmedCharacterName, "vMatrix");
    if (saved?.levels && Object.keys(saved.levels).length > 0) onChange(JSON.stringify(saved.levels));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const levels = parseLevels(value);

  function setLevel(name: string, level: number) {
    onChange(JSON.stringify({ ...levels, [name]: level }));
  }

  if (!classId || loadFailed) {
    return (
      <SetupStepFrame theme={theme} stepLabel={step.label} stepNumber={stepNumber} totalSteps={totalSteps}
        description="V Matrix data is not available for this class yet."
        onBack={onBack} onNext={onNext} onFinish={onFinish}
      >
        <p style={{ margin: 0, fontSize: "0.85rem", color: theme.muted, fontWeight: 700 }}>
          No data available for {jobName || "this class"}.
        </p>
      </SetupStepFrame>
    );
  }

  return (
    <SetupStepFrame theme={theme} stepLabel={step.label} stepNumber={stepNumber} totalSteps={totalSteps}
      description="All fields are optional. Fill in what you know."
      onBack={onBack} onNext={onNext} onFinish={onFinish}
    >
      {catalog ? (
        <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
          <NodeSection label="Job Nodes" nodes={catalog.job} max={JOB_MAX} levels={levels} theme={theme} onSet={setLevel} />
          <NodeSection label="Boost Nodes" nodes={catalog.boost} max={BOOST_MAX} levels={levels} theme={theme} onSet={setLevel} />
          <NodeSection label="Common Nodes" nodes={catalog.common} max={COMMON_MAX} levels={levels} theme={theme} onSet={setLevel} />
        </div>
      ) : (
        <p style={{ margin: 0, fontSize: "0.85rem", color: theme.muted, fontWeight: 700 }}>Loading…</p>
      )}
    </SetupStepFrame>
  );
}
