/*
  Shared types for class skill data plus a per-class dynamic-import loader.
  Each class's data lives in its own file so the bundler code-splits by class —
  visiting /guides/character-guides/hero loads only hero.ts, not all 52 classes.

  Auto-generated by scripts/scrape-class-skills.mjs. Do not edit by hand.
*/

export interface ClassSkillLevel {
  level: number;
  effect: string;
}

/**
 * Numeric job tier, derived from the wiki heading icon:
 *   1 — 1st Job (beginner skills fold in here)
 *   2 — 2nd Job
 *   3 — 3rd Job
 *   4 — 4th Job (Hyper Skills fold in here)
 *   5 — 5th Job / V Skills
 *   6 — 6th Job / HEXA Skills
 */
export type JobTier = 1 | 2 | 3 | 4 | 5 | 6;

export interface ClassSkill {
  name: string;
  icon: string;
  category?: string;
  section: string;
  job: string;
  jobTier: JobTier;
  masterLevel?: number;
  prerequisite?: string;
  description?: string;
  levels?: ClassSkillLevel[];
}

export interface ClassSkillSet {
  className: string;
  skills: ClassSkill[];
}

const LOADERS: Record<string, () => Promise<ClassSkillSet>> = {
  "Hero": () => import("./hero").then((m) => m.default),
  "Paladin": () => import("./paladin").then((m) => m.default),
  "Dark Knight": () => import("./dark-knight").then((m) => m.default),
  "Arch Mage (Fire/Poison)": () => import("./arch-mage-firepoison").then((m) => m.default),
  "Arch Mage (Ice/Lightning)": () => import("./arch-mage-icelightning").then((m) => m.default),
  "Bishop": () => import("./bishop").then((m) => m.default),
  "Bow Master": () => import("./bow-master").then((m) => m.default),
  "Marksman": () => import("./marksman").then((m) => m.default),
  "Pathfinder": () => import("./pathfinder").then((m) => m.default),
  "Night Lord": () => import("./night-lord").then((m) => m.default),
  "Shadower": () => import("./shadower").then((m) => m.default),
  "Dual Blade": () => import("./dual-blade").then((m) => m.default),
  "Corsair": () => import("./corsair").then((m) => m.default),
  "Cannoneer": () => import("./cannoneer").then((m) => m.default),
  "Buccaneer": () => import("./buccaneer").then((m) => m.default),
  "Dawn Warrior": () => import("./dawn-warrior").then((m) => m.default),
  "Blaze Wizard": () => import("./blaze-wizard").then((m) => m.default),
  "Wind Archer": () => import("./wind-archer").then((m) => m.default),
  "Night Walker": () => import("./night-walker").then((m) => m.default),
  "Thunder Breaker": () => import("./thunder-breaker").then((m) => m.default),
  "Mihile": () => import("./mihile").then((m) => m.default),
  "Aran": () => import("./aran").then((m) => m.default),
  "Evan": () => import("./evan").then((m) => m.default),
  "Mercedes": () => import("./mercedes").then((m) => m.default),
  "Phantom": () => import("./phantom").then((m) => m.default),
  "Luminous": () => import("./luminous").then((m) => m.default),
  "Shade": () => import("./shade").then((m) => m.default),
  "Battle Mage": () => import("./battle-mage").then((m) => m.default),
  "Wild Hunter": () => import("./wild-hunter").then((m) => m.default),
  "Mechanic": () => import("./mechanic").then((m) => m.default),
  "Blaster": () => import("./blaster").then((m) => m.default),
  "Xenon": () => import("./xenon").then((m) => m.default),
  "Demon Slayer": () => import("./demon-slayer").then((m) => m.default),
  "Demon Avenger": () => import("./demon-avenger").then((m) => m.default),
  "Kaiser": () => import("./kaiser").then((m) => m.default),
  "Angelic Buster": () => import("./angelic-buster").then((m) => m.default),
  "Cadena": () => import("./cadena").then((m) => m.default),
  "Kain": () => import("./kain").then((m) => m.default),
  "Illium": () => import("./illium").then((m) => m.default),
  "Ark": () => import("./ark").then((m) => m.default),
  "Adele": () => import("./adele").then((m) => m.default),
  "Khali": () => import("./khali").then((m) => m.default),
  "Hoyoung": () => import("./hoyoung").then((m) => m.default),
  "Lara": () => import("./lara").then((m) => m.default),
  "Ren": () => import("./ren").then((m) => m.default),
  "Zero": () => import("./zero").then((m) => m.default),
  "Kinesis": () => import("./kinesis").then((m) => m.default),
  "Hayato": () => import("./hayato").then((m) => m.default),
  "Kanna": () => import("./kanna").then((m) => m.default),
  "Lynn": () => import("./lynn").then((m) => m.default),
  "Mo Xuan": () => import("./mo-xuan").then((m) => m.default),
  "Sia Astelle": () => import("./sia-astelle").then((m) => m.default),
};

const cache = new Map<string, Promise<ClassSkillSet | undefined>>();

export function loadClassSkills(className: string): Promise<ClassSkillSet | undefined> {
  if (!cache.has(className)) {
    const loader = LOADERS[className];
    cache.set(className, loader ? loader() : Promise.resolve(undefined));
  }
  return cache.get(className)!;
}
