/*
  Community resource links per class (Discord servers, class docs, wikis, etc.).
  Auto-generated by scripts/scrape-class-resources.mjs. Do not edit by hand.
*/

type ResourceType = "discord" | "doc" | "wiki" | "infographic" | "other";

export interface ClassResource {
  label: string;
  url: string;
  type: ResourceType;
}

export const CLASS_RESOURCES: Record<string, ClassResource[]> = {
  "Hero": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Hero", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%ED%9E%88%EC%96%B4%EB%A1%9C(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/dsdSz9CGJE", type: "discord" },
    { label: "Class Doc", url: "https://buffhero.win/", type: "doc" },
  ],
  "Paladin": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Paladin", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%ED%8C%94%EB%9D%BC%EB%94%98(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/7qyGfmtRt2", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1aAQV9QGR4UywDGhQq1O3X7blXADPGDMvgDIAKfCmrH8", type: "doc" },
    { label: "UltimateNPC's Guide", url: "https://youtu.be/q99Xr0_RPzQ", type: "doc" },
  ],
  "Dark Knight": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Dark_Knight", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%8B%A4%ED%81%AC%EB%82%98%EC%9D%B4%ED%8A%B8(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/N36cqyAVfa", type: "discord" },
  ],
  "Arch Mage (Fire/Poison)": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Arch_Mage_(Fire,_Poison)", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%95%84%ED%81%AC%EB%A9%94%EC%9D%B4%EC%A7%80(%EB%B6%88%2C%EB%8F%85)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/PX2v4BV3Qp", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1hsu7SjHUrRZDIyqXW8DJ_8qVHTVmb5UGeRh3Ipfw7JQ/edit?tab=t.0", type: "doc" },
    { label: "Infographic", url: "/infographics/arch-mage-fire-poison-infographic.webp", type: "infographic" },
  ],
  "Arch Mage (Ice/Lightning)": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Arch_Mage_(Ice,_Lightning)", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%95%84%ED%81%AC%EB%A9%94%EC%9D%B4%EC%A7%80(%EC%8D%AC%2C%EC%BD%9C)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/PX2v4BV3Qp", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1fVI8tdEwBDigRD9HTcVIYtoFhm1ggXzsJMlIG_9_lAk/edit?tab=t.0#heading=h.yhb0ijl9ccrv", type: "doc" },
    { label: "Infographic", url: "/infographics/arch-mage-ice-lightning-infographic.webp", type: "infographic" },
  ],
  "Bishop": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Bishop", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%B9%84%EC%88%8D(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/PX2v4BV3Qp", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/11OaoVNl-VacN7XncfLWJxlHmAIePB10fhwWNT8WVf38/edit?tab=t.0#heading=h.vdn8atyw677l", type: "doc" },
    { label: "Infographic", url: "/infographics/bishop-infographic.webp", type: "infographic" },
  ],
  "Bow Master": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Bowmaster", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%B3%B4%EC%9A%B0%EB%A7%88%EC%8A%A4%ED%84%B0", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/YJqyRYxWV3", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/14Ob3MKysPnv7aQ31uLm0SkBLpKZSSjKRuwh_2nn28HE", type: "doc" },
    { label: "Sky's Guide", url: "https://dexless.com/guides/bowmaster-in-depth-job-guide.137/", type: "doc" },
  ],
  "Marksman": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Marksman", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%8B%A0%EA%B6%81(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/BYvnXkz9cv", type: "discord" },
  ],
  "Pathfinder": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Pathfinder", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%ED%8C%A8%EC%8A%A4%ED%8C%8C%EC%9D%B8%EB%8D%94(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/4PgsVs8gNZ", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/e/2PACX-1vQAthq_f1FtuK1M6PRNsV1j9MMKJHK1LW7eMVhq4hAUfPYS0okmhJZ_oEsKHBJoYgpzkioA_uiBmrtA/pub", type: "doc" },
  ],
  "Night Lord": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Night_Lord", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%82%98%EC%9D%B4%ED%8A%B8%EB%A1%9C%EB%93%9C", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/AvP8wq4", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/16GI6FLwcS3aunYHqXsOEuqQIZ3g5N8V3SHc--RyW8X8", type: "doc" },
  ],
  "Shadower": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Shadower", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%84%80%EB%8F%84%EC%96%B4", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/3NKFYxR2T3", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1NKBCWe9a2P2RKo8jScEv5EjAj4hVWsBu-9DW9dZMTvI", type: "doc" },
  ],
  "Dual Blade": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Dual_Blade", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%93%80%EC%96%BC%EB%B8%94%EB%A0%88%EC%9D%B4%EB%93%9C", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/sv8JuUqBGQ", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1Z4GXLiVTJOj2o6GM2tNZtzN5z6qO7-pGJ8JX82qj66s", type: "doc" },
  ],
  "Corsair": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Corsair", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%BA%A1%ED%8B%B4(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/eNFCVDuGbB", type: "discord" },
    { label: "Class Doc", url: "https://cutt.ly/corsairfaq", type: "doc" },
  ],
  "Cannoneer": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Cannoneer", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%BA%90%EB%85%BC%EC%8A%88%ED%84%B0", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/XJzkgQRPcM", type: "discord" },
  ],
  "Buccaneer": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Buccaneer", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%B0%94%EC%9D%B4%ED%8D%BC(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/EPxuyRy", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1M1jTSVxLkmXLbt1Dpwh9yP3D7yO7SIL5FWD6HCFweAo", type: "doc" },
  ],
  "Dawn Warrior": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Dawn_Warrior", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%86%8C%EC%9A%B8%EB%A7%88%EC%8A%A4%ED%84%B0", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/WMGahCmmWT", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1iQfiF7q78bmZtBujnLcAkDNDjqiHqm7iZ2QjUfKRd-g", type: "doc" },
  ],
  "Blaze Wizard": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Blaze_Wizard", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%ED%94%8C%EB%A0%88%EC%9E%84%EC%9C%84%EC%9E%90%EB%93%9C", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/gTuaWGrcvV", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1YB3rBntxbUngJ5BnCTG19SqW1LfoPos6pfS-r5gaU1s", type: "doc" },
    { label: "TajMaJon's Guide", url: "https://www.youtube.com/watch?v=5sBhhpDQX8E", type: "doc" },
  ],
  "Wind Archer": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Wind_Archer", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%9C%88%EB%93%9C%EB%B8%8C%EB%A0%88%EC%9D%B4%EC%BB%A4(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/4pbZMeThgP", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1oqZegwzp5pzOArQ_NKYpoYZTxkV_8kq_3W_EQ8SzSDc", type: "doc" },
  ],
  "Night Walker": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Night_Walker", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%82%98%EC%9D%B4%ED%8A%B8%EC%9B%8C%EC%BB%A4", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/FR55ADj", type: "discord" },
  ],
  "Thunder Breaker": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Thunder_Breaker", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%8A%A4%ED%8A%B8%EB%9D%BC%EC%9D%B4%EC%BB%A4(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/ewyWwFQ", type: "discord" },
  ],
  "Mihile": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Mihile", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%AF%B8%ED%95%98%EC%9D%BC(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/6SPVvZRWJM", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1PQKPlHGbvqT7dftm2-jk9i8SiBLRkaY5E0DpE0unK5I/", type: "doc" },
  ],
  "Aran": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Aran", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%95%84%EB%9E%80(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/WpJ4VDta8V", type: "discord" },
  ],
  "Evan": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Evan", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%97%90%EB%B0%98(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/5BfVGGD", type: "discord" },
    { label: "Evanovation's Guide", url: "https://sites.google.com/view/evanandmir", type: "doc" },
  ],
  "Mercedes": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Mercedes", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%A9%94%EB%A5%B4%EC%84%B8%EB%8D%B0%EC%8A%A4(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/tJWfMrdFBJ", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1Sz5rdODR3cgaw3WcfjjVN_OBQV2298vc_kVyFOfdh_8", type: "doc" },
  ],
  "Phantom": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Phantom", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%ED%8C%AC%ED%85%80(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/225H7sw", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1rrl6haeeYpeYaCuDhqbK_qL_IMBbRPbF60D-hq0vgSg", type: "doc" },
  ],
  "Luminous": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Luminous", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%A3%A8%EB%AF%B8%EB%84%88%EC%8A%A4(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/KBpPTtae6P", type: "discord" },
  ],
  "Shade": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Shade", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%9D%80%EC%9B%94", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/G86EwxDbv6", type: "discord" },
  ],
  "Battle Mage": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Battle_Mage", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%B0%B0%ED%8B%80%EB%A9%94%EC%9D%B4%EC%A7%80(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/HsTgS8svrf", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1GSP16fN2SZC0f7StnHpyzxk_90NjTL337LkwbC_9yfM", type: "doc" },
  ],
  "Wild Hunter": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Wild_Hunter", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%99%80%EC%9D%BC%EB%93%9C%ED%97%8C%ED%84%B0", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/3evaYBDwAG", type: "discord" },
    { label: "Infographic", url: "/infographics/wild-hunter-infographic.webp", type: "infographic" },
  ],
  "Mechanic": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Mechanic", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%A9%94%EC%B9%B4%EB%8B%89(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/JenpnsgHBc", type: "discord" },
  ],
  "Blaster": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Blaster", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%B8%94%EB%9E%98%EC%8A%A4%ED%84%B0(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/QXvbNp8zqu", type: "discord" },
  ],
  "Xenon": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Xenon", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%A0%9C%EB%85%BC(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/4BCGuCC", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1bpARm1tksZ2LdVCBWoClaNlyjEhvs0IHJqQShr1o99M", type: "doc" },
  ],
  "Demon Slayer": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Demon_Slayer", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%8D%B0%EB%AA%AC%20%EC%8A%AC%EB%A0%88%EC%9D%B4%EC%96%B4(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/XpJA3u8Scd", type: "discord" },
  ],
  "Demon Avenger": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Demon_Avenger", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%8D%B0%EB%AA%AC%20%EC%96%B4%EB%B2%A4%EC%A0%B8", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/aTByagnDjd", type: "discord" },
  ],
  "Kaiser": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Kaiser", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%B9%B4%EC%9D%B4%EC%A0%80(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.com/invite/DGHZJ8s", type: "discord" },
    { label: "Class Doc", url: "https://tinyurl.com/RebootKaiserGuide", type: "doc" },
  ],
  "Angelic Buster": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Angelic_Buster", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%97%94%EC%A0%A4%EB%A6%AD%EB%B2%84%EC%8A%A4%ED%84%B0", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/angelicbuster", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/13ceGRfEU9iULpAX7Fm3xtO1zrkDL4lWMqY3jmcbZOpc", type: "doc" },
    { label: "Infographic", url: "/infographics/angelic-buster-infographic.webp", type: "infographic" },
  ],
  "Cadena": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Cadena", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%B9%B4%EB%8D%B0%EB%82%98", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/5rKRYYCA4v", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1mpmXgE5pWITvp3OHlV0LTmekFiXoZr4Zdb8X_Kv2i14", type: "doc" },
  ],
  "Kain": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Kain", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%B9%B4%EC%9D%B8(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/Udtx9E9QYr", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1Vl-G1C_bWzDio13cSnROD3RA1EoeR4mMjv28g_UY4dY", type: "doc" },
  ],
  "Illium": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Illium", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%9D%BC%EB%A6%AC%EC%9B%80", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/KxJ3DGuBsf", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1yRtTynFk6jNthJlBwCSTeM4rcV3taEnwx9DOJ9MzBds", type: "doc" },
  ],
  "Ark": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Ark", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%95%84%ED%81%AC(,%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/ZvPTz6v", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1fA0jEOp5pUikqDUht0GadFPTzhxYTWZTVO_rNkz9erQ", type: "doc" },
    { label: "Infographic", url: "/infographics/ark-infographic.webp", type: "infographic" },
  ],
  "Adele": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Adele", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%95%84%EB%8D%B8(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/q7tYdfT", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1FYhaPrUcSZtJM19-oxnKyVocewpHro9w3pTkwg3IiKU", type: "doc" },
  ],
  "Khali": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Khali", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%B9%BC%EB%A6%AC(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/an6dkrgXTr", type: "discord" },
  ],
  "Hoyoung": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Hoyoung", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%ED%98%B8%EC%98%81(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/aWprrWUTAJ", type: "discord" },
    { label: "Class Doc", url: "https://www.hoyoung.directory", type: "doc" },
  ],
  "Lara": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Lara", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%9D%BC%EB%9D%BC(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/g33kJR5yWH", type: "discord" },
  ],
  "Ren": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Ren", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%A0%8C(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/52rC3geGqC", type: "discord" },
    { label: "Myst's Guide", url: "https://www.youtube.com/watch?v=RhhFZLPpzYs", type: "doc" },
    { label: "Infographic", url: "/infographics/ren-infographic.webp", type: "infographic" },
  ],
  "Zero": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Zero", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%A0%9C%EB%A1%9C(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/wFAHprps3Z", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1ygEhU_gZjm6tY8ngi0hzZ6ZduNoGuZqdcPsiMV1pdf8", type: "doc" },
  ],
  "Kinesis": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Kinesis", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%ED%82%A4%EB%84%A4%EC%8B%9C%EC%8A%A4", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/yua4VdQWFw", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1eOsYMHVZMeb9X85p5K-O4JLIN15ifkczxTAuwS657OI", type: "doc" },
  ],
  "Hayato": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Hayato", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%ED%95%98%EC%95%BC%ED%86%A0(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/EAkfmrx", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1P4mBaIAc-YgycrtemcaUmuo13YRkbA0FP-MbJb1fzIo", type: "doc" },
    { label: "Infographic", url: "/infographics/hayato-infographic.webp", type: "infographic" },
  ],
  "Kanna": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Kanna", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%B9%B8%EB%82%98(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/zbH8e2xC7H", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1oYnMextDLHVgI7p9mrQTCxeGvf_AKtRb7UrpZyTFT5s", type: "doc" },
    { label: "Infographic", url: "/infographics/kanna-infographic.webp", type: "infographic" },
  ],
  "Lynn": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Lynn", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%A6%B0(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/czcga75tHQ", type: "discord" },
  ],
  "Mo Xuan": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Mo_Xuan", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EB%AC%B5%ED%98%84", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/a3z6JYmHbt", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1ZhYf1f5c6MXkNaicqkIYMQegiUUYwo5vlxoNdeJcxKM", type: "doc" },
    { label: "Infographic", url: "/infographics/mo-xuan-infographic.webp", type: "infographic" },
  ],
  "Sia Astelle": [
    { label: "MapleStory Wiki", url: "https://maplestorywiki.net/w/Sia_Astelle", type: "wiki" },
    { label: "NamuWiki", url: "https://en.namu.wiki/w/%EC%8B%9C%EC%95%84%20%EC%95%84%EC%8A%A4%ED%85%94", type: "wiki" },
    { label: "Class Discord", url: "https://discord.gg/9pUBfTsntS", type: "discord" },
    { label: "Class Doc", url: "https://docs.google.com/document/d/1l4anp8MVMuIAMpcGj9WLQgMRhpjTIgKbMlNj9KHx2CI", type: "doc" },
  ],
};
