/*
  Centralized UI copy for characters setup flow.
  Edit wording here to update all related components.
*/
export const CHARACTERS_COPY = {
  firstTimeSetup: {
    title: "First-Time Setup",
    subtitle: "Choose how you want to get started.",
    importButton: "Import Character",
    searchButton: "Search Character",
  },
  importCharacter: {
    title: "Import Character",
    subtitlePrefix: "Choose a JSON or Image file from a character's",
    subtitleSuffix: "Export.",
    backButton: "Back",
    pickFileButton: "Choose File",
    chooseDifferentFileButton: "Choose a different file",
    addCharacterButton: "Add Character",
    invalidJsonError: "That file isn't valid JSON.",
    invalidPngError: "That image doesn't have any MapleDoro character data in it.",
    invalidShapeError: "That file doesn't look like a MapleDoro character export.",
    wrongFileTypeWorldError: "That's a world export, not a single character.",
    roleLabel: "Add as",
    roleMule: "Mule",
    roleMain: "Main",
    roleChampion: "Champion",
  },
  worldImport: {
    title: "Import World",
    subtitlePrefix: "Choose a JSON file from an",
    subtitleSuffix: "Export World.",
    backButton: "Back",
    invalidJsonError: "That file isn't valid JSON.",
    invalidShapeError: "That file doesn't look like a MapleDoro world export.",
    wrongFileTypeCharacterError: "That's a single character export, not a world.",
    tooManyCharactersError: "That file has more characters than a world export can legitimately contain. It may have been modified.",
    duplicateCharacterError: "That file has a duplicate character in it. It may have been modified.",
    conflictSummaryPrefix: "of",
    conflictSummarySuffix: "characters already exist on this world.",
    legionDataConflict: "This world already has Legion Artifact data saved.",
    keepAllMine: "Keep all existing",
    useAllImported: "Use all imported",
    customizeButton: "Customize",
    confirmButton: "Confirm Import",
    newCharacterCountSuffix: "new character(s) will be added with no conflicts.",
    residentCountSuffix: "characters already on this world aren't in this file.",
    characterCapSuffix: "characters on this world",
    championCountSuffix: "champions on this world",
    characterCapErrorPrefix: "This world can only hold",
    characterCapErrorSuffix: "characters. Uncheck some new or existing characters above to continue.",
    mainConflictPrefix: "and",
    mainConflictSuffix: "can't both be Main. Change one of their role choices above to continue.",
    championOverflowPrefix: "This world can only have",
    championOverflowMiddle: "champions, but",
    championOverflowSuffix: "would end up assigned. Change some role choices above to continue.",
    dropNewCharacterRoleButton: "Make Mule",
    restoreNewCharacterRoleButton: "Undo Mule",
  },
  importConflict: {
    titleSuffix: "already exists",
    subtitle: "Choose which version to keep for each section.",
    keepMine: "Keep existing",
    useImported: "Use imported",
    keepAllMine: "Keep all existing",
    useAllImported: "Use all imported",
    roleLabel: "Main/Champion/Mule Role",
    cancelButton: "Cancel",
    confirmButton: "Confirm",
  },
  championSwap: {
    title: "Champion slots are full",
    subtitle: "Pick one to swap out.",
    cancelButton: "Cancel",
    confirmButton: "Confirm Swap",
  },
  searchEntry: {
    title: "Add Your Character",
    subtitle: "Type your IGN to setup your profile.",
    backButton: "Back",
    backToCharactersButton: "← Characters",
    searchButton: "Search",
    searchingButton: "Searching...",
  },
  searchResultPreview: {
    confirmPrompt: "Is this the character you want to add?",
    confirmButton: "Confirm",
  },
  quickSetupIntro: {
    firstTitle: "Let's go through the first setup",
    firstSubtitle: "This is your first character, we'll go through it one step at a time.",
    additionalTitle: "Let's set up this character",
    additionalSubtitle: "We'll go through it one step at a time.",
    nextStepButton: "Next Step",
  },
  characterProfile: {
    backButton: "Back",
    viewYourCharactersButton: "Characters",
  },
  characterProfileActions: {
    setMainButton: "Set main",
    removeMainButton: "Remove main",
    setChampionButton: "Set champion",
    removeChampionButton: "Remove champion",
    removeCharacterButton: "Remove",
  },
  characterDirectory: {
    title: "View Your Characters",
    sortRowsLabel: "Sort rows",
    sortAlphabeticalOption: "Alphabetical",
    sortByLevelOption: "By Level",
    sortByClassOption: "By Class",
    sortByWorldOption: "By World",
    mainCharacterLabel: "Main Character",
    championsLabel: "Champions",
    mulesLabel: "Mules",
    addCharacterButton: "Add character",
    noMainSelectedMessage: "No main selected yet.",
    noCharactersAddedMessage: "No characters added yet.",
    mainAlsoChampionMessage: "Main is also set as champion.",
  },
} as const;
